apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocketd
spec:
  selector:
    matchLabels:
      app: websocketd
  template:
    metadata:
      labels:
        app: websocketd
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: websocketd
        image: websocketd:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: websocketd
spec:
  type: NodePort
  selector:
    app: websocketd
  ports:
  - name: http
    port: 8181
    targetPort: 8181
    nodePort: 30081
